version: '3.9'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app_network
    restart: always
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: hw02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: always
    container_name: goit_hw02_app
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    networks:
      - app_network
    restart: always
networks:
  app_network:
    driver: bridge
